import { Inter, Roboto } from 'next/font/google';
import './globals.css';
import Globalnav from '../../components/globalnav';
import 'normalize.css/normalize.css';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  weight: ['100', '300', '400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Apple clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />
      </head>
      <body className={roboto.className}>
        <Globalnav />
        {children}
      </body>
    </html>
  );
}
